### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by waytoomuchgaming** [p1tcode/SpellAnnouncerClassic#28]
Message: Interface\AddOns\SpellAnnouncerClassic\Options.lua:735: attempt to index field '?' (a nil value)
Time: Mon Mar  2 07:23:04 2020
Count: 1
Stack: Interface\AddOns\SpellAnnouncerClassic\Options.lua:735: attempt to index field '?' (a nil value)
Interface\AddOns\SpellAnnouncerClassic\Options.lua:735: in function `?'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:225: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1202: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1144: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1648: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1928: in function `Open'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1956: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1954>
[C]: ?
...face\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:72: in function <...face\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
...face\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:290: in function `Fire'
...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:20: in function <...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:19>
[C]: in function `Show'
Interface\FrameXML\InterfaceOptionsFrame.lua:28: in function `InterfaceOptionsList_DisplayPanel'
Interface\FrameXML\InterfaceOptionsFrame.lua:46: in function `InterfaceOptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals: <none>

**Comment by p1tcode** [comment]
This happens if you have a spell or aura selected and I remove that spell from the spell list when updating to a new version. Selecting on of the available spells should solve the problem.
